routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
*/

Route::get('/', function () {
    return redirect(route('dashboard.posts.index'));
})->name('index');

Route::resource('posts', 'PostController')->except('show');
Route::resource('categories', 'CategoryController')->except('show');

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([ 'register' => false ]);

Route::get('/', 'BlogController@index')->name('blog.index');
Route::get('/{post}', 'BlogController@show')->name('blog.show');

app/Models/Post.php
<?php

namespace NetzeeBlog\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    const COVER_PATH = 'public/posts/cover';
    const COVER_PATH_URL = 'storage/posts/cover';

    protected $fillable = [ 'title', 'status', 'description', 'cover' ];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function coverUrl()
    {
        return asset(self::COVER_PATH_URL.'/'.$this->cover);
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace NetzeeBlog\Http\Controllers\Dashboard;

use Illuminate\Http\Response;
use Illuminate\Http\Request;
use NetzeeBlog\Http\Requests\Category as RequestCategory;
use NetzeeBlog\Models\Category;
use NetzeeBlog\Http\Controllers\Controller;
use NetzeeBlog\Services\Category as ServiceCategory;

class CategoryController extends Controller
{
    /**
     * @var ServiceCategory
     */
    protected $serviceCategory;

    public function __construct(ServiceCategory $serviceCategory)
    {
        $this->serviceCategory = $serviceCategory;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $categories = $this->serviceCategory->filterPaginate($request);
        return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  RequestCategory $request
     * @return Response
     */
    public function store(RequestCategory $request)
    {
        $category = $this->serviceCategory->saveCategory($request);
        return redirect()
            ->route('dashboard.categories.edit', [ 'categories' => $category ])
            ->with('success', 'Categoria salva com sucesso.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category  $category
     * @return Response
     */
    public function edit(Category $category)
    {
        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RequestCategory $request
     * @param Category $category
     * @return Response
     */
    public function update(RequestCategory $request, Category $category)
    {
        $category = $this->serviceCategory->saveCategory($request, $category);
        return redirect()
            ->route('dashboard.categories.edit', [ 'categories' => $category ])
            ->with('success', 'Categoria salva com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category  $category
     * @return Response
     */
    public function destroy(Category $category)
    {
        try {
            $this->serviceCategory->deleteCategoryDetachPosts($category);
            return redirect()
                ->route('dashboard.categories.index')
                ->with('success', 'Categoria removida com sucesso.');
        } catch (\Exception $e) {
            return redirect()
                ->route('dashboard.categories.edit', [ 'categories' => $category ])
                ->withErrors([ $e->getMessage() ]);
        }
    }
}

app/Http/Controllers/Dashboard/PostController.php
<?php

namespace NetzeeBlog\Http\Controllers\Dashboard;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Response;
use NetzeeBlog\Http\Controllers\Controller;
use Illuminate\Http\Request;
use NetzeeBlog\Http\Requests\Post as RequestPost;
use NetzeeBlog\Models\Post;
use NetzeeBlog\Repositories\Category;
use NetzeeBlog\Services\Post as ServicePost;

class PostController extends Controller
{
    /**
     * @var ServicePost|Builder
     */
    private $servicePost;

    /**
     * @var Category
     */
    private $category;

    public function __construct(ServicePost $post, Category $category)
    {
        $this->servicePost = $post;
        $this->category= $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $posts = $this->servicePost->filterPaginate($request);
        return view('dashboard.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = $this->category->all(false, false);
        return view('dashboard.posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RequestPost $request
     * @return Response
     */
    public function store(RequestPost $request)
    {
        $post = $this->servicePost->savePostWithCategories($request);
        return redirect()
            ->route('dashboard.posts.edit', [ 'posts' => $post ])
            ->with('success', 'Artigo salvo com sucesso.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return Response
     */
    public function edit(Post $post)
    {
        $categories = $this->category->all(false, false);
        $postCategoryIds = $post->categories()->allRelatedIds()->toArray();
        return view('dashboard.posts.edit', compact('post', 'categories', 'postCategoryIds'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RequestPost $request
     * @param  Post $post
     * @return Response
     */
    public function update(RequestPost $request, Post $post)
    {
        $post = $this->servicePost->savePostWithCategories($request, $post);
        return redirect()
            ->route('dashboard.posts.edit', [ 'posts' => $post ])
            ->with('success', 'Artigo salvo com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Post $post
     * @return Response
     * @throws \Exception
     */
    public function destroy(Post $post)
    {
        try {
            $this->servicePost->deletePostDetachCategories($post);
            return redirect()
                ->route('dashboard.posts.index')
                ->with('success', 'Artigo removido com sucesso.');
        } catch (\Exception $e) {
            return redirect()
                ->route('dashboard.posts.edit', [ 'posts' => $post ])
                ->withErrors([ $e->getMessage() ]);
        }
    }
}

resources/views/dashboard/posts/create.blade.php
@extends('adminlte::page')

@section('title', 'NetzeeBlog - Novo Artigo')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Novo Artigo</h3>
        </div>
        <form role="form" action="{{ route('dashboard.posts.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="box-body">
                <div class="form-group">
                    <label for="title">Título</label>
                    <input type="text" name="title" class="form-control" id="title" placeholder="Título" value="{{ old('title') }}">
                </div>
                <div class="form-group">
                    <label for="status">Status</label>
                    <select name="status" class="form-control select2" id="status">
                        <option value="1" selected>Ativo</option>
                        <option value="0">Inativo</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="cover">Imagem de capa</label>
                    <input type="file" name="cover" id="cover">
                </div>
                <div class="form-group">
                    <label for="categories">Categorias</label>
                    <select name="categories[]" class="form-control select2" id="categories" multiple>
                        @foreach($categories as $category)
                            <option
                                value="{{ $category->id }}"
                                {{ in_array($category->id, old('categories', [])) ? 'selected' : '' }}>
                                {{ $category->title }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <textarea class="form-control editor" name="description">{!! old('description') !!}</textarea>
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
@stop

resources/views/dashboard/posts/edit.blade.php
@extends('adminlte::page')

@section('title', 'NetzeeBlog - Editar Artigo')

@section('content')
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Editar Artigo</h3>

            <div class="box-tools">
                <form class="delete-register" action="{{ route('dashboard.posts.destroy', [ $post ]) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-sm btn-danger">
                        <i class="fa fa-remove"></i>
                        Excluir
                    </button>
                </form>
            </div>
        </div>
        <form role="form" action="{{ route('dashboard.posts.update', [ $post ]) }}" method="POST" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="box-body">
                <div class="form-group">
                    <label for="title">Título</label>
                    <input type="text" name="title" class="form-control" id="title" placeholder="Título" value="{{ $post->title }}">
                </div>
                <div class="form-group">
                    <label for="status">Status</label>
                    <select name="status" class="form-control select2" id="status">
                        <option value="1" {{ $post->status === 1 ? 'selected' : '' }}>Ativo</option>
                        <option value="0" {{ $post->status === 0 ? 'selected' : '' }}>Inativo</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="cover">Imagem de capa</label>
                    <input type="file" name="cover" id="cover">
                </div>
                <div class="form-group">
                    <label for="categories">Categorias</label>
                    <select name="categories[]" class="form-control select2" id="categories" multiple>
                        @foreach($categories as $category)
                            <option
                                value="{{ $category->id }}"
                                {{ in_array($category->id, $postCategoryIds) ? 'selected' : '' }}>
                                {{ $category->title }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <textarea class="form-control editor" name="description">{!! $post->description !!}</textarea>
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
@stop

resources/views/dashboard/posts/index.blade.php
@extends('adminlte::page')

@section('title', 'NetzeeBlog - Artigos')

@section('content')
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Artigos</h3>

            <div class="box-tools">
                <form action="{{ route('dashboard.posts.index') }}">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Buscar">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            <a href="{{ url()->current() }}" type="reset" class="btn btn-warning"><i class="fa fa-ban"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Descrição</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($posts as $post)
                        <tr data-href="{{ route('dashboard.posts.edit', [$post]) }}" style="cursor: pointer;">
                            <td>{{ str_limit($post->title, 50, '...') }}</td>
                            <td>{{ str_limit(strip_tags($post->description), 100, '...') }}</td>
                            <td>
                                <span class="label label-{{ $post->status ? 'success' : 'danger' }}">
                                    {{ $post->status ? 'Ativo' : 'Inativo' }}
                                </span>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" align="center">Nenhum registro encontrado</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        <div class="box-footer clearfix">
            <div class="no-margin pull-right">
                {{ $posts->links() }}
            </div>
        </div>
    </div>
@stop